name: .NET Core

on:
  push:
    branches: [ "lab2", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore UniversityStats/UniversityStats.sln
    - name: Build
      run: dotnet build UniversityStats/UniversityStats.sln --no-restore
    - name: Test
      run: dotnet test UniversityStats/UniversityStats.sln --no-build --verbosity normal
